---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r eval=TRUE}
library(quanteda)
library(dplyr)
library(tidyverse)
library(utf8)
library(ggplot2)


setwd("D:/Universidad/Minería de datos 2/actividad-ayudantia-2")
primer_tiempo2020 <- read_csv("Primer_Tiempo2020.csv", col_names = TRUE)

#str(primer_tiempo2020)
#attach(primer_tiempo2020)
summary(primer_tiempo2020)

primer_tiempo2020

primer_tiempo2020 <- primer_tiempo2020[,!(colnames(primer_tiempo2020) %in% c("id_partido", "fasepartido", "local", "tiempo","formationUsed", "torneo"))]
primer_tiempo2020


fh2020 <- primer_tiempo2020[order(primer_tiempo2020$accuratePass, decreasing = TRUE),]
fh2020


fh2020_pases = fh2020[,colnames(primer_tiempo2020) %in% c("equipo", "partido", "accuratePass", "totalPass", "precision_pases")]
fh2020_pases = fh2020_pases[order(fh2020_pases$precision_pases, decreasing = TRUE),]

fh2020_pases

fh2020_tiros <- NULL

fh2020_tiros = fh2020[,colnames(primer_tiempo2020) %in% c("equipo", "partido", "goals", "ontargetScoringAtt", "totalScoringAtt", "blockedScoringAtt", "shotOffTarget", "precision_tiros")]
fh2020_tiros = fh2020_tiros[order(fh2020_tiros$goals, decreasing = TRUE),]
fh2020_tiros


Uchile <- filter(primer_tiempo2020, equipo == "Universidad de Chile")
Uchile_tiros <- filter(fh2020_tiros, equipo == "Universidad de Chile")
Uchile_pases <- filter(fh2020_pases, equipo == "Universidad de Chile")


Uchile_pases <- Uchile_pases[,!(colnames(Uchile_pases) %in% c("equipo"))] 

Promedios_Pas <- c("Promedio Pases",mean(Uchile_pases$accuratePass),mean(Uchile_pases$totalPass),mean(Uchile_pases$precision_pases))
Uchile_pases <- rbind(Uchile_pases, Promedios_Pas)

Max_Pas <- c("Max Pases",max(Uchile_pases$accuratePass),max(Uchile_pases$totalPass),max(Uchile$precision_pases))
Uchile_pases <- rbind(Uchile_pases, Max_Pas)

Min_Pas <- c("Min Pases",min(Uchile_pases$accuratePass),min(Uchile_pases$totalPass),min(Uchile_pases$precision_pases))
Uchile_pases <- rbind(Uchile_pases, Min_Pas)

Uchile_pases

pases_Uchile <- Uchile$accuratePass
Uchile2 <- Uchile[order(Uchile$accuratePass, decreasing = FALSE),]

#dotchart(huachipato$totalPass, labels = huachipato$partido, cex=0.5, xlab = "Pases", ylab = "Partido")

dotchart(Uchile$totalPass, labels = utf8_encode(Uchile$partido), cex=0.5, xlab = "Pases", ylab = "Partido")


dotchart(Uchile$accuratePass, labels = utf8_encode(Uchile$partido), cex=0.5, xlab = "Pases", ylab = "Partido")



dotchart(Uchile2$totalPass, labels = utf8_encode(Uchile$partido), cex=0.5, xlab = "Pases", ylab = "Partido")


dotchart(Uchile2$totalPass, labels = utf8_encode(Uchile$partido), main="Pases Acertados Uchile", pch = 16, col=c("darkblue","dodgerblue"),lcolor="gray90", cex=0.8, xlab = "Pases", ylab = "Partido", cex.main=2,cex.lab=1.5)



texto <- primer_tiempo2020$partido
texto <- char_tolower(texto)
texto <- iconv(texto, to = "ASCII//TRANSLIT")

a <- dfm(texto, remove = c(stopwords("es"), "vs", "Universidad"))
dim(a)

```

